remote_theme: pages-themes/primer@v0.6.0  
plugins:
- jekyll-remote-theme  
title: CSC Research Data Hub Workshops Materials
description: Materials to support workshops delivered through UBCO's Centre for Scholarly Communication Research Data Hub